- hosts: zos_host
  collections:
    - ibm.ibm_zos_ims
  gather_facts: no

  environment: "{{ environment_vars }}"
  vars_files:
    - "ims_commands.yml"

  # loop over tasks specified in command_tasks.yml
  tasks:
    - name: run IMS command and print output
      include_tasks: command_tasks.yml
      loop: '{{ commands }}'



